version: '3.8'

services:
  web:
    image: php:8.2-apache
    container_name: laravel_web
    volumes:
      - '.:/var/www/html'
      - './php.ini:/usr/local/etc/php/php.ini'  # Se precisar de uma configuração PHP personalizada
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpass
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    networks:
      - app-network

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - '.:/app'
    working_dir: /app
    command: ["composer", "install"]

networks:
  app-network:
    driver: bridge

volumes:
  db_data: